{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "d7998a22-5633-465c-8f9a-6d03b5d5d0b4",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2025-05-15 10:15:13.568 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-15 10:15:13.570 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-15 10:15:15.408 \n",
      "  \u001b[33m\u001b[1mWarning:\u001b[0m to view this Streamlit app on a browser, run it with the following\n",
      "  command:\n",
      "\n",
      "    streamlit run C:\\Users\\User\\anaconda3\\envs\\TF\\lib\\site-packages\\ipykernel_launcher.py [ARGUMENTS]\n",
      "2025-05-15 10:15:15.408 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-15 10:15:15.416 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-15 10:15:15.420 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-15 10:15:15.429 No runtime found, using MemoryCacheStorageManager\n",
      "2025-05-15 10:15:15.438 No runtime found, using MemoryCacheStorageManager\n",
      "2025-05-15 10:15:15.445 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-15 10:15:15.450 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-15 10:15:15.460 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-15 10:15:15.746 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-15 10:15:15.751 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-15 10:15:15.980 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-15 10:15:15.986 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-15 10:15:16.001 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-15 10:15:16.560 Thread 'Thread-4': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-15 10:15:16.568 Thread 'Thread-4': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-15 10:15:20.824 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-15 10:15:20.827 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-15 10:15:21.040 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-15 10:15:21.042 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-15 10:15:21.045 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-15 10:15:21.048 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-15 10:15:21.057 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-15 10:15:21.061 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-15 10:15:21.074 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-15 10:15:21.183 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-15 10:15:21.183 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-15 10:15:21.191 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-15 10:15:21.199 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-15 10:15:21.215 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-15 10:15:21.217 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-15 10:15:21.222 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-15 10:15:21.230 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-15 10:15:21.238 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-15 10:15:21.246 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-15 10:15:21.250 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-15 10:15:21.261 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-15 10:15:21.264 Session state does not function when running a script without `streamlit run`\n",
      "2025-05-15 10:15:21.268 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-15 10:15:21.275 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-15 10:15:21.488 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-15 10:15:23.499 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-15 10:15:23.499 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-15 10:15:23.499 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-15 10:15:23.528 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-15 10:15:23.537 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n"
     ]
    }
   ],
   "source": [
    "import streamlit as st\n",
    "import pandas as pd\n",
    "import joblib\n",
    "import matplotlib.pyplot as plt\n",
    "\n",
    "# Configuration de la page\n",
    "st.set_page_config(page_title=\"Application NOx\", layout=\"wide\")\n",
    "\n",
    "st.title(\" Prédiction de la pollution NOx\")\n",
    "st.markdown(\"Cette application utilise deux modèles pour prédire les niveaux de NOx et détecter les alertes.\")\n",
    "\n",
    "# 1. Chargement des données\n",
    "@st.cache_data\n",
    "def load_data():\n",
    "    df = pd.read_csv(\"Nox.csv\")\n",
    "    df['date'] = pd.to_datetime(df['date'], format=\"%d.%m.%Y %H:%M\")\n",
    "    return df\n",
    "\n",
    "df = load_data()\n",
    "\n",
    "# 2. Préparation des features\n",
    "features = df.drop(['date', 'Nox_baf', 'Nox opsis'], axis=1)\n",
    "features = features.apply(pd.to_numeric, errors='coerce')\n",
    "features = features.fillna(features.mean())\n",
    "\n",
    "# 3. Chargement des modèles\n",
    "@st.cache_resource\n",
    "def load_models():\n",
    "    model_baf = joblib.load(\"Nox1_modèle.pkl\")\n",
    "    model_opsis = joblib.load(\"Nox_opsis_linearregression.pkl\")\n",
    "    return model_baf, model_opsis\n",
    "\n",
    "model_baf, model_opsis = load_models()\n",
    "\n",
    "# 4. Prédictions\n",
    "df['Nox_baf_pred'] = model_baf.predict(features)\n",
    "df['Nox_opsis_pred'] = model_opsis.predict(features)\n",
    "\n",
    "# 5. Fonctions d’alerte\n",
    "def alerte_baf(val):\n",
    "    if val >= 500:\n",
    "        return \" DANGER\"\n",
    "    elif val >= 400:\n",
    "        return \" ATTENTION\"\n",
    "    else:\n",
    "        return \" OK\"\n",
    "\n",
    "def alerte_opsis(val):\n",
    "    if val >= 450:\n",
    "        return \" DANGER\"\n",
    "    elif val >= 350:\n",
    "        return \" ATTENTION\"\n",
    "    else:\n",
    "        return \" OK\"\n",
    "\n",
    "df['Alerte_baf'] = df['Nox_baf_pred'].apply(alerte_baf)\n",
    "df['Alerte_opsis'] = df['Nox_opsis_pred'].apply(alerte_opsis)\n",
    "\n",
    "# 6. Affichage des alertes\n",
    "st.subheader(\" Statistiques d'alerte\")\n",
    "\n",
    "col1, col2 = st.columns(2)\n",
    "\n",
    "with col1:\n",
    "    st.write(\"**NOx BAF**\")\n",
    "    st.dataframe(df['Alerte_baf'].value_counts().rename_axis(\"Alerte\").reset_index(name=\"Nombre\"))\n",
    "\n",
    "with col2:\n",
    "    st.write(\"**NOx OPSIS**\")\n",
    "    st.dataframe(df['Alerte_opsis'].value_counts().rename_axis(\"Alerte\").reset_index(name=\"Nombre\"))\n",
    "\n",
    "# 7. Tracés interactifs\n",
    "st.subheader(\"📈 Visualisation des prédictions\")\n",
    "\n",
    "target_option = st.selectbox(\"Choisissez le type de NOx à afficher :\", [\"Nox_baf\", \"Nox_opsis\"])\n",
    "\n",
    "if target_option == \"Nox_baf\":\n",
    "    col_pred = \"Nox_baf_pred\"\n",
    "    col_alert = \"Alerte_baf\"\n",
    "    seuils = [500, 400]\n",
    "else:\n",
    "    col_pred = \"Nox_opsis_pred\"\n",
    "    col_alert = \"Alerte_opsis\"\n",
    "    seuils = [450, 350]\n",
    "\n",
    "colors = {\" OK\": \"green\", \" ATTENTION\": \"orange\", \" DANGER\": \"red\"}\n",
    "\n",
    "fig, ax = plt.subplots(figsize=(14, 6))\n",
    "\n",
    "for alrt, color in colors.items():\n",
    "    subset = df[df[col_alert] == alrt]\n",
    "    ax.scatter(subset['date'], subset[col_pred], label=alrt, color=color, s=10)\n",
    "\n",
    "for seuil in seuils:\n",
    "    ax.axhline(y=seuil, color='red' if seuil == seuils[0] else 'orange', linestyle='--', linewidth=1.5, label=f'Seuil {seuil}')\n",
    "\n",
    "ax.set_title(f\"Prédictions et alertes pour {target_option}\")\n",
    "ax.set_xlabel(\"Date\")\n",
    "ax.set_ylabel(f\"{target_option} prédit\")\n",
    "ax.grid(True)\n",
    "ax.legend()\n",
    "st.pyplot(fig)\n",
    "\n",
    "# 8. Affichage optionnel des données\n",
    "with st.expander(\" Voir les données complètes\"):\n",
    "    st.dataframe(df[['date', 'Nox_baf_pred', 'Nox_opsis_pred', 'Alerte_baf', 'Alerte_opsis']])\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.18"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
