{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "d7998a22-5633-465c-8f9a-6d03b5d5d0b4",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2025-05-15 10:15:13.568 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-15 10:15:13.570 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-15 10:15:15.408 \n",
      "  \u001b[33m\u001b[1mWarning:\u001b[0m to view this Streamlit app on a browser, run it with the following\n",
      "  command:\n",
      "\n",
      "    streamlit run C:\\Users\\User\\anaconda3\\envs\\TF\\lib\\site-packages\\ipykernel_launcher.py [ARGUMENTS]\n",
      "2025-05-15 10:15:15.408 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-15 10:15:15.416 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-15 10:15:15.420 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-15 10:15:15.429 No runtime found, using MemoryCacheStorageManager\n",
      "2025-05-15 10:15:15.438 No runtime found, using MemoryCacheStorageManager\n",
      "2025-05-15 10:15:15.445 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-15 10:15:15.450 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-15 10:15:15.460 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-15 10:15:15.746 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-15 10:15:15.751 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-15 10:15:15.980 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-15 10:15:15.986 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-15 10:15:16.001 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-15 10:15:16.560 Thread 'Thread-4': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-15 10:15:16.568 Thread 'Thread-4': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-15 10:15:20.824 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-15 10:15:20.827 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-15 10:15:21.040 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-15 10:15:21.042 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-15 10:15:21.045 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-15 10:15:21.048 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-15 10:15:21.057 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-15 10:15:21.061 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-15 10:15:21.074 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-15 10:15:21.183 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-15 10:15:21.183 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-15 10:15:21.191 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-15 10:15:21.199 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-15 10:15:21.215 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-15 10:15:21.217 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-15 10:15:21.222 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-15 10:15:21.230 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-15 10:15:21.238 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-15 10:15:21.246 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-15 10:15:21.250 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-15 10:15:21.261 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-15 10:15:21.264 Session state does not function when running a script without `streamlit run`\n",
      "2025-05-15 10:15:21.268 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-15 10:15:21.275 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-15 10:15:21.488 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-15 10:15:23.499 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-15 10:15:23.499 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-15 10:15:23.499 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-15 10:15:23.528 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-15 10:15:23.537 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n"
     ]
    }
   ],
   "source": [
    "import streamlit as st\n",
    "import pandas as pd\n",
    "import joblib\n",
    "import matplotlib.pyplot as plt\n",
    "\n",
    "# Configuration de la page\n",
    "st.set_page_config(page_title=\"Application NOx\", layout=\"wide\")\n",
    "\n",
    "st.title(\"Prédiction de la pollution NOx\")\n",
    "st.markdown(\"Cette application utilise deux modèles pour prédire les niveaux de NOx et détecter les alertes.\")\n",
    "\n",
    "# 1. Téléchargement des données par l'utilisateur\n",
    "st.subheader(\"📁 Téléchargez vos données\")\n",
    "uploaded_file = st.file_uploader(\"Choisissez un fichier CSV\", type=\"csv\")\n",
    "\n",
    "if uploaded_file:\n",
    "    # Chargement des données depuis le fichier téléchargé avec gestion des valeurs manquantes\n",
    "    try:\n",
    "        df = pd.read_csv(uploaded_file, na_values=[\"null\", \"NaN\", \"NA\"])\n",
    "        # Conversion de la colonne 'date' en datetime\n",
    "        df['date'] = pd.to_datetime(df['date'], format=\"%d.%m.%Y %H:%M\")\n",
    "    except Exception as e:\n",
    "        st.error(f\"Erreur lors du chargement des données : {e}\")\n",
    "        st.stop()\n",
    "\n",
    "    st.write(\"Voici un aperçu des données :\")\n",
    "    st.dataframe(df.head())\n",
    "\n",
    "    # 2. Préparation des features\n",
    "    features = df.drop(['date', 'Nox_baf', 'Nox opsis'], axis=1)\n",
    "    features = features.apply(pd.to_numeric, errors='coerce')\n",
    "    features = features.fillna(features.mean())\n",
    "\n",
    "    # 3. Chargement des modèles\n",
    "    @st.cache_resource\n",
    "    def load_models():\n",
    "        model_baf = joblib.load(\"Nox1_modèle.pkl\")\n",
    "        model_opsis = joblib.load(\"Nox_opsis_linearregression.pkl\")\n",
    "        return model_baf, model_opsis\n",
    "\n",
    "    model_baf, model_opsis = load_models()\n",
    "\n",
    "    # 4. Prédictions\n",
    "    df['Nox_baf_pred'] = model_baf.predict(features)\n",
    "    df['Nox_opsis_pred'] = model_opsis.predict(features)\n",
    "\n",
    "    # 5. Fonctions d’alerte\n",
    "    def alerte_baf(val):\n",
    "        if val >= 500:\n",
    "            return \"DANGER\"\n",
    "        elif val >= 400:\n",
    "            return \"ATTENTION\"\n",
    "        else:\n",
    "            return \"OK\"\n",
    "\n",
    "    def alerte_opsis(val):\n",
    "        if val >= 450:\n",
    "            return \"DANGER\"\n",
    "        elif val >= 350:\n",
    "            return \"ATTENTION\"\n",
    "        else:\n",
    "            return \"OK\"\n",
    "\n",
    "    df['Alerte_baf'] = df['Nox_baf_pred'].apply(alerte_baf)\n",
    "    df['Alerte_opsis'] = df['Nox_opsis_pred'].apply(alerte_opsis)\n",
    "\n",
    "    # 6. Affichage des alertes sous forme de graphique\n",
    "    st.subheader(\"Distribution des alertes\")\n",
    "\n",
    "    alert_baf_counts = df['Alerte_baf'].value_counts()\n",
    "    alert_opsis_counts = df['Alerte_opsis'].value_counts()\n",
    "\n",
    "    # Graphiques à barres\n",
    "    fig_alert_baf, ax_alert_baf = plt.subplots()\n",
    "    ax_alert_baf.bar(alert_baf_counts.index, alert_baf_counts.values, color=['green', 'orange', 'red'])\n",
    "    ax_alert_baf.set_title(\"Distribution des alertes NOx BAF\")\n",
    "    ax_alert_baf.set_xlabel(\"Alerte\")\n",
    "    ax_alert_baf.set_ylabel(\"Nombre d'occurrences\")\n",
    "    st.pyplot(fig_alert_baf)\n",
    "\n",
    "    fig_alert_opsis, ax_alert_opsis = plt.subplots()\n",
    "    ax_alert_opsis.bar(alert_opsis_counts.index, alert_opsis_counts.values, color=['green', 'orange', 'red'])\n",
    "    ax_alert_opsis.set_title(\"Distribution des alertes NOx OPSIS\")\n",
    "    ax_alert_opsis.set_xlabel(\"Alerte\")\n",
    "    ax_alert_opsis.set_ylabel(\"Nombre d'occurrences\")\n",
    "    st.pyplot(fig_alert_opsis)\n",
    "\n",
    "    # 7. Affichage interactif des prédictions avec filtre par date\n",
    "    st.subheader(\"📈 Visualisation des prédictions\")\n",
    "\n",
    "    target_option = st.selectbox(\"Choisissez le type de NOx à afficher :\", [\"Nox_baf\", \"Nox_opsis\"])\n",
    "\n",
    "    # Sélection de la plage de dates\n",
    "    start_date, end_date = st.date_input(\n",
    "        \"Sélectionner la plage de dates\",\n",
    "        [df['date'].min(), df['date'].max()],\n",
    "        min_value=df['date'].min(),\n",
    "        max_value=df['date'].max()\n",
    "    )\n",
    "\n",
    "    # Filtrer les données selon la plage de dates\n",
    "    df_filtered = df[(df['date'] >= pd.to_datetime(start_date)) & (df['date'] <= pd.to_datetime(end_date))]\n",
    "\n",
    "    if target_option == \"Nox_baf\":\n",
    "        col_pred = \"Nox_baf_pred\"\n",
    "        col_alert = \"Alerte_baf\"\n",
    "        seuils = [500, 400]\n",
    "    else:\n",
    "        col_pred = \"Nox_opsis_pred\"\n",
    "        col_alert = \"Alerte_opsis\"\n",
    "        seuils = [450, 350]\n",
    "\n",
    "    colors = {\"OK\": \"green\", \"ATTENTION\": \"orange\", \"DANGER\": \"red\"}\n",
    "\n",
    "    fig, ax = plt.subplots(figsize=(14, 6))\n",
    "\n",
    "    for alrt, color in colors.items():\n",
    "        subset = df_filtered[df_filtered[col_alert] == alrt]\n",
    "        ax.scatter(subset['date'], subset[col_pred], label=alrt, color=color, s=10)\n",
    "\n",
    "    for seuil in seuils:\n",
    "        ax.axhline(y=seuil, color='red' if seuil == seuils[0] else 'orange', linestyle='--', linewidth=1.5, label=f'Seuil {seuil}')\n",
    "\n",
    "    ax.set_title(f\"Prédictions et alertes pour {target_option}\")\n",
    "    ax.set_xlabel(\"Date\")\n",
    "    ax.set_ylabel(f\"{target_option} prédit\")\n",
    "    ax.grid(True)\n",
    "    ax.legend()\n",
    "    st.pyplot(fig)\n",
    "\n",
    "    # 8. Téléchargement des résultats sous forme de CSV\n",
    "    st.subheader(\"📥 Télécharger les résultats\")\n",
    "\n",
    "    @st.cache_data\n",
    "    def convert_df(df):\n",
    "        return df.to_csv(index=False).encode('utf-8')\n",
    "\n",
    "    csv = convert_df(df[['date', 'Nox_baf_pred', 'Nox_opsis_pred', 'Alerte_baf', 'Alerte_opsis']])\n",
    "\n",
    "    st.download_button(\n",
    "        label=\"Télécharger les résultats\",\n",
    "        data=csv,\n",
    "        file_name='resultats_predictions.csv',\n",
    "        mime='text/csv'\n",
    "    )\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.18"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
